# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: web-app-secrets
  namespace: production
type: Opaque
stringData:
  database_password: ${DATABASE_PASSWORD} # This will be handled by my CI/CD pipeline