apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - secret.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - networkpolicy.yaml
  - pdb.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: web-app
  app.kubernetes.io/component: frontend
  app.kubernetes.io/part-of: web-platform